name: Compile

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - run: cargo fetch --target x86_64-pc-windows-msvc
            - run: cargo build --target x86_64-pc-windows-msvc --release
            - uses: actions/upload-artifact@v3
              if: success()
              with:
                  name: NW-Macro-Engine.exe
                  path: target/release/
                  retention-days: 5
