name: Compile & Test

on:
    push:
        branches: [master]

jobs:
    release-setup:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v3
            - name: "Fetch Dependencies"
              run: cargo fetch --target x86_64-pc-windows-gnu
            - name: "Run Rust Tests"
              run: cargo test --target x86_64-pc-windows-gnu
            - name: "Build"
              run: cargo build --target x86_64-pc-windows-gnu --release
            - uses: actions/upload-artifact@v3
              if: success()
              with:
                  name: nw-macro-engine.exe
                  path: target/x86_64-pc-windows-gnu/release/nw-macro-engine.exe
                  retention-days: 5
